/**
 * @module emoji-data
 * @description Curated set of ~500 emojis organized by category for the
 * EmojiPicker component. Entries are sorted by popularityRank within each
 * category (most popular first). Only standard Unicode emoji are used.
 */

import type { EmojiItem } from '@coexist/wisp-core/types/EmojiPicker.types';

// ---------------------------------------------------------------------------
// Smileys & Emotion (~60)
// ---------------------------------------------------------------------------

const smileys: EmojiItem[] = [
  { emoji: '\u{1F602}', name: 'face with tears of joy', keywords: ['laugh', 'crying', 'happy', 'lol'], category: 'smileys', popularityRank: 1 },
  { emoji: '\u{1F923}', name: 'rolling on the floor laughing', keywords: ['rofl', 'lol', 'laugh', 'funny'], category: 'smileys', popularityRank: 3 },
  { emoji: '\u{1F62D}', name: 'loudly crying face', keywords: ['cry', 'sad', 'tears', 'upset'], category: 'smileys', popularityRank: 5 },
  { emoji: '\u{1F60D}', name: 'smiling face with heart-eyes', keywords: ['love', 'crush', 'adore', 'heart'], category: 'smileys', popularityRank: 6 },
  { emoji: '\u{1F525}', name: 'fire', keywords: ['hot', 'flame', 'lit', 'burn'], category: 'smileys', popularityRank: 7 },
  { emoji: '\u{1F614}', name: 'pensive face', keywords: ['sad', 'thoughtful', 'sorry'], category: 'smileys', popularityRank: 8 },
  { emoji: '\u{1F60A}', name: 'smiling face with smiling eyes', keywords: ['happy', 'blush', 'smile', 'joy'], category: 'smileys', popularityRank: 10 },
  { emoji: '\u{2764}\u{FE0F}', name: 'red heart', keywords: ['love', 'heart', 'romance', 'valentine'], category: 'smileys', popularityRank: 11 },
  { emoji: '\u{1F629}', name: 'weary face', keywords: ['tired', 'exhausted', 'upset'], category: 'smileys', popularityRank: 13 },
  { emoji: '\u{1F970}', name: 'smiling face with hearts', keywords: ['love', 'adore', 'crush', 'infatuated'], category: 'smileys', popularityRank: 14 },
  { emoji: '\u{1F62A}', name: 'sleepy face', keywords: ['tired', 'sleep', 'drowsy'], category: 'smileys', popularityRank: 16 },
  { emoji: '\u{1F60E}', name: 'smiling face with sunglasses', keywords: ['cool', 'confident', 'swag'], category: 'smileys', popularityRank: 17 },
  { emoji: '\u{1F601}', name: 'beaming face with smiling eyes', keywords: ['grin', 'happy', 'smile', 'joy'], category: 'smileys', popularityRank: 19 },
  { emoji: '\u{1F609}', name: 'winking face', keywords: ['wink', 'flirt', 'playful'], category: 'smileys', popularityRank: 21 },
  { emoji: '\u{1F622}', name: 'crying face', keywords: ['cry', 'sad', 'tear', 'upset'], category: 'smileys', popularityRank: 23 },
  { emoji: '\u{1F618}', name: 'face blowing a kiss', keywords: ['kiss', 'love', 'flirt', 'heart'], category: 'smileys', popularityRank: 25 },
  { emoji: '\u{1F604}', name: 'grinning face with smiling eyes', keywords: ['smile', 'happy', 'grin'], category: 'smileys', popularityRank: 27 },
  { emoji: '\u{1F62E}\u200D\u{1F4A8}', name: 'face exhaling', keywords: ['sigh', 'relief', 'exhale', 'breathe'], category: 'smileys', popularityRank: 29 },
  { emoji: '\u{1F605}', name: 'grinning face with sweat', keywords: ['nervous', 'awkward', 'sweat', 'hot'], category: 'smileys', popularityRank: 31 },
  { emoji: '\u{1F633}', name: 'flushed face', keywords: ['embarrassed', 'shocked', 'blush'], category: 'smileys', popularityRank: 33 },
  { emoji: '\u{1F643}', name: 'upside-down face', keywords: ['sarcasm', 'silly', 'ironic'], category: 'smileys', popularityRank: 35 },
  { emoji: '\u{1F60F}', name: 'smirking face', keywords: ['smirk', 'flirt', 'suggestive'], category: 'smileys', popularityRank: 37 },
  { emoji: '\u{1F612}', name: 'unamused face', keywords: ['annoyed', 'bored', 'unimpressed'], category: 'smileys', popularityRank: 39 },
  { emoji: '\u{1F621}', name: 'pouting face', keywords: ['angry', 'mad', 'rage', 'furious'], category: 'smileys', popularityRank: 41 },
  { emoji: '\u{1F97A}', name: 'pleading face', keywords: ['beg', 'puppy eyes', 'please', 'cute'], category: 'smileys', popularityRank: 43 },
  { emoji: '\u{1F631}', name: 'face screaming in fear', keywords: ['scared', 'horror', 'shocked', 'scream'], category: 'smileys', popularityRank: 45 },
  { emoji: '\u{1F624}', name: 'face with steam from nose', keywords: ['angry', 'frustrated', 'mad'], category: 'smileys', popularityRank: 47 },
  { emoji: '\u{1F611}', name: 'expressionless face', keywords: ['blank', 'meh', 'deadpan'], category: 'smileys', popularityRank: 49 },
  { emoji: '\u{1F60B}', name: 'face savoring food', keywords: ['yummy', 'delicious', 'tasty', 'tongue'], category: 'smileys', popularityRank: 51 },
  { emoji: '\u{1F61C}', name: 'winking face with tongue', keywords: ['silly', 'playful', 'tongue', 'wink'], category: 'smileys', popularityRank: 53 },
  { emoji: '\u{1F61E}', name: 'disappointed face', keywords: ['sad', 'unhappy', 'bummed'], category: 'smileys', popularityRank: 55 },
  { emoji: '\u{1F634}', name: 'sleeping face', keywords: ['sleep', 'zzz', 'tired', 'snore'], category: 'smileys', popularityRank: 57 },
  { emoji: '\u{1F637}', name: 'face with medical mask', keywords: ['sick', 'ill', 'mask', 'covid'], category: 'smileys', popularityRank: 59 },
  { emoji: '\u{1F92F}', name: 'exploding head', keywords: ['mind blown', 'shocked', 'amazed'], category: 'smileys', popularityRank: 61 },
  { emoji: '\u{1F913}', name: 'nerd face', keywords: ['nerd', 'geek', 'glasses', 'smart'], category: 'smileys', popularityRank: 63 },
  { emoji: '\u{1F607}', name: 'smiling face with halo', keywords: ['angel', 'innocent', 'good', 'holy'], category: 'smileys', popularityRank: 65 },
  { emoji: '\u{1F608}', name: 'smiling face with horns', keywords: ['devil', 'evil', 'naughty', 'mischief'], category: 'smileys', popularityRank: 67 },
  { emoji: '\u{1F92E}', name: 'face vomiting', keywords: ['sick', 'puke', 'gross', 'disgusting'], category: 'smileys', popularityRank: 69 },
  { emoji: '\u{1F975}', name: 'hot face', keywords: ['hot', 'sweating', 'heat'], category: 'smileys', popularityRank: 71 },
  { emoji: '\u{1F976}', name: 'cold face', keywords: ['cold', 'freezing', 'ice', 'winter'], category: 'smileys', popularityRank: 73 },
  { emoji: '\u{1F910}', name: 'zipper-mouth face', keywords: ['secret', 'quiet', 'mute', 'zip'], category: 'smileys', popularityRank: 75 },
  { emoji: '\u{1F914}', name: 'thinking face', keywords: ['think', 'hmm', 'wonder', 'consider'], category: 'smileys', popularityRank: 77 },
  { emoji: '\u{1F928}', name: 'face with raised eyebrow', keywords: ['skeptical', 'suspicious', 'doubt'], category: 'smileys', popularityRank: 79 },
  { emoji: '\u{1F644}', name: 'face with rolling eyes', keywords: ['eyeroll', 'annoyed', 'whatever'], category: 'smileys', popularityRank: 81 },
  { emoji: '\u{1F636}', name: 'face without mouth', keywords: ['speechless', 'mute', 'silent'], category: 'smileys', popularityRank: 83 },
  { emoji: '\u{1F92D}', name: 'face with hand over mouth', keywords: ['oops', 'giggle', 'gasp', 'cover'], category: 'smileys', popularityRank: 85 },
  { emoji: '\u{1F971}', name: 'yawning face', keywords: ['bored', 'tired', 'yawn', 'sleepy'], category: 'smileys', popularityRank: 87 },
  { emoji: '\u{1F917}', name: 'hugging face', keywords: ['hug', 'embrace', 'warm', 'comfort'], category: 'smileys', popularityRank: 89 },
  { emoji: '\u{1F920}', name: 'cowboy hat face', keywords: ['cowboy', 'western', 'yeehaw'], category: 'smileys', popularityRank: 91 },
  { emoji: '\u{1F911}', name: 'money-mouth face', keywords: ['money', 'rich', 'cash', 'dollar'], category: 'smileys', popularityRank: 93 },
  { emoji: '\u{1F922}', name: 'nauseated face', keywords: ['sick', 'gross', 'nausea', 'queasy'], category: 'smileys', popularityRank: 95 },
  { emoji: '\u{1F635}', name: 'face with crossed-out eyes', keywords: ['dizzy', 'dead', 'knocked out'], category: 'smileys', popularityRank: 97 },
  { emoji: '\u{1F47B}', name: 'ghost', keywords: ['halloween', 'spooky', 'scary', 'boo'], category: 'smileys', popularityRank: 99 },
  { emoji: '\u{1F47D}', name: 'alien', keywords: ['ufo', 'extraterrestrial', 'space'], category: 'smileys', popularityRank: 101 },
  { emoji: '\u{1F916}', name: 'robot', keywords: ['bot', 'machine', 'android', 'ai'], category: 'smileys', popularityRank: 103 },
  { emoji: '\u{1F4A9}', name: 'pile of poo', keywords: ['poop', 'crap', 'funny'], category: 'smileys', popularityRank: 105 },
  { emoji: '\u{1F921}', name: 'clown face', keywords: ['clown', 'joker', 'circus', 'funny'], category: 'smileys', popularityRank: 107 },
  { emoji: '\u{1F480}', name: 'skull', keywords: ['dead', 'death', 'skeleton', 'scary'], category: 'smileys', popularityRank: 109 },
  { emoji: '\u{1F383}', name: 'jack-o-lantern', keywords: ['halloween', 'pumpkin', 'spooky'], category: 'smileys', popularityRank: 111 },
  { emoji: '\u{1F47F}', name: 'angry face with horns', keywords: ['devil', 'demon', 'angry', 'evil'], category: 'smileys', popularityRank: 113 },
  { emoji: '\u{1F600}', name: 'grinning face', keywords: ['smile', 'happy', 'grin', 'teeth'], category: 'smileys', popularityRank: 115 },
  { emoji: '\u{1F603}', name: 'grinning face with big eyes', keywords: ['smile', 'happy', 'joy'], category: 'smileys', popularityRank: 117 },
  { emoji: '\u{1F606}', name: 'grinning squinting face', keywords: ['laugh', 'happy', 'haha', 'xd'], category: 'smileys', popularityRank: 119 },
  { emoji: '\u{1F61A}', name: 'kissing face with closed eyes', keywords: ['kiss', 'love', 'smooch'], category: 'smileys', popularityRank: 121 },
  { emoji: '\u{1F61D}', name: 'squinting face with tongue', keywords: ['silly', 'tongue', 'playful', 'tease'], category: 'smileys', popularityRank: 123 },
  { emoji: '\u{1F92A}', name: 'zany face', keywords: ['crazy', 'wild', 'silly', 'goofy'], category: 'smileys', popularityRank: 125 },
  { emoji: '\u{1F615}', name: 'confused face', keywords: ['confused', 'puzzled', 'huh'], category: 'smileys', popularityRank: 127 },
  { emoji: '\u{1F630}', name: 'anxious face with sweat', keywords: ['nervous', 'anxious', 'worried', 'sweat'], category: 'smileys', popularityRank: 129 },
  { emoji: '\u{1F628}', name: 'fearful face', keywords: ['scared', 'fear', 'worried', 'nervous'], category: 'smileys', popularityRank: 131 },
];

// ---------------------------------------------------------------------------
// People & Body (~80)
// ---------------------------------------------------------------------------

const people: EmojiItem[] = [
  { emoji: '\u{1F44D}', name: 'thumbs up', keywords: ['like', 'approve', 'yes', 'ok'], category: 'people', skinToneSupport: true, popularityRank: 4 },
  { emoji: '\u{1F64F}', name: 'folded hands', keywords: ['pray', 'please', 'thanks', 'hope'], category: 'people', skinToneSupport: true, popularityRank: 9 },
  { emoji: '\u{1F44F}', name: 'clapping hands', keywords: ['clap', 'applause', 'bravo', 'congrats'], category: 'people', skinToneSupport: true, popularityRank: 12 },
  { emoji: '\u{1F44C}', name: 'ok hand', keywords: ['ok', 'perfect', 'fine', 'nice'], category: 'people', skinToneSupport: true, popularityRank: 15 },
  { emoji: '\u{1F44B}', name: 'waving hand', keywords: ['wave', 'hello', 'hi', 'bye'], category: 'people', skinToneSupport: true, popularityRank: 18 },
  { emoji: '\u{270C}\u{FE0F}', name: 'victory hand', keywords: ['peace', 'victory', 'two'], category: 'people', skinToneSupport: true, popularityRank: 20 },
  { emoji: '\u{1F4AA}', name: 'flexed biceps', keywords: ['strong', 'muscle', 'power', 'flex'], category: 'people', skinToneSupport: true, popularityRank: 22 },
  { emoji: '\u{1F44E}', name: 'thumbs down', keywords: ['dislike', 'no', 'bad', 'disapprove'], category: 'people', skinToneSupport: true, popularityRank: 24 },
  { emoji: '\u{1F91D}', name: 'handshake', keywords: ['deal', 'agree', 'partnership', 'meeting'], category: 'people', skinToneSupport: true, popularityRank: 26 },
  { emoji: '\u{1F64B}', name: 'person raising hand', keywords: ['raise hand', 'question', 'volunteer'], category: 'people', skinToneSupport: true, popularityRank: 28 },
  { emoji: '\u{1F918}', name: 'sign of the horns', keywords: ['rock', 'metal', 'horns', 'cool'], category: 'people', skinToneSupport: true, popularityRank: 30 },
  { emoji: '\u{1F448}', name: 'backhand index pointing left', keywords: ['point', 'left', 'direction'], category: 'people', skinToneSupport: true, popularityRank: 32 },
  { emoji: '\u{1F449}', name: 'backhand index pointing right', keywords: ['point', 'right', 'direction'], category: 'people', skinToneSupport: true, popularityRank: 34 },
  { emoji: '\u{261D}\u{FE0F}', name: 'index pointing up', keywords: ['point', 'up', 'one', 'first'], category: 'people', skinToneSupport: true, popularityRank: 36 },
  { emoji: '\u{1F44A}', name: 'oncoming fist', keywords: ['punch', 'fist bump', 'power'], category: 'people', skinToneSupport: true, popularityRank: 38 },
  { emoji: '\u{1F64C}', name: 'raising hands', keywords: ['celebrate', 'hooray', 'praise', 'yay'], category: 'people', skinToneSupport: true, popularityRank: 40 },
  { emoji: '\u{1F91E}', name: 'crossed fingers', keywords: ['luck', 'hope', 'wish', 'fingers crossed'], category: 'people', skinToneSupport: true, popularityRank: 42 },
  { emoji: '\u{1F919}', name: 'call me hand', keywords: ['call', 'shaka', 'hang loose', 'phone'], category: 'people', skinToneSupport: true, popularityRank: 44 },
  { emoji: '\u{1F590}\u{FE0F}', name: 'hand with fingers splayed', keywords: ['hand', 'five', 'high five', 'stop'], category: 'people', skinToneSupport: true, popularityRank: 46 },
  { emoji: '\u{270A}', name: 'raised fist', keywords: ['fist', 'power', 'solidarity', 'strong'], category: 'people', skinToneSupport: true, popularityRank: 48 },
  { emoji: '\u{1F91F}', name: 'love-you gesture', keywords: ['ily', 'love', 'hand sign'], category: 'people', skinToneSupport: true, popularityRank: 50 },
  { emoji: '\u{1F595}', name: 'middle finger', keywords: ['rude', 'finger', 'flip off'], category: 'people', skinToneSupport: true, popularityRank: 52 },
  { emoji: '\u{1F937}', name: 'person shrugging', keywords: ['shrug', 'idk', 'whatever', 'dunno'], category: 'people', skinToneSupport: true, popularityRank: 54 },
  { emoji: '\u{1F926}', name: 'person facepalming', keywords: ['facepalm', 'smh', 'disappointed'], category: 'people', skinToneSupport: true, popularityRank: 56 },
  { emoji: '\u{1F645}', name: 'person gesturing no', keywords: ['no', 'stop', 'deny', 'disagree'], category: 'people', skinToneSupport: true, popularityRank: 58 },
  { emoji: '\u{1F646}', name: 'person gesturing ok', keywords: ['ok', 'yes', 'agree'], category: 'people', skinToneSupport: true, popularityRank: 60 },
  { emoji: '\u{1F647}', name: 'person bowing', keywords: ['bow', 'sorry', 'respect', 'apology'], category: 'people', skinToneSupport: true, popularityRank: 62 },
  { emoji: '\u{1F481}', name: 'person tipping hand', keywords: ['sassy', 'info', 'help'], category: 'people', skinToneSupport: true, popularityRank: 64 },
  { emoji: '\u{1F471}', name: 'person with blond hair', keywords: ['blond', 'person', 'hair'], category: 'people', skinToneSupport: true, popularityRank: 66 },
  { emoji: '\u{1F468}', name: 'man', keywords: ['male', 'boy', 'guy', 'man'], category: 'people', skinToneSupport: true, popularityRank: 68 },
  { emoji: '\u{1F469}', name: 'woman', keywords: ['female', 'girl', 'lady', 'woman'], category: 'people', skinToneSupport: true, popularityRank: 70 },
  { emoji: '\u{1F476}', name: 'baby', keywords: ['infant', 'child', 'newborn'], category: 'people', skinToneSupport: true, popularityRank: 72 },
  { emoji: '\u{1F474}', name: 'old man', keywords: ['elderly', 'grandpa', 'grandfather', 'senior'], category: 'people', skinToneSupport: true, popularityRank: 74 },
  { emoji: '\u{1F475}', name: 'old woman', keywords: ['elderly', 'grandma', 'grandmother', 'senior'], category: 'people', skinToneSupport: true, popularityRank: 76 },
  { emoji: '\u{1F466}', name: 'boy', keywords: ['child', 'kid', 'young', 'male'], category: 'people', skinToneSupport: true, popularityRank: 78 },
  { emoji: '\u{1F467}', name: 'girl', keywords: ['child', 'kid', 'young', 'female'], category: 'people', skinToneSupport: true, popularityRank: 80 },
  { emoji: '\u{1F385}', name: 'santa claus', keywords: ['christmas', 'santa', 'holiday', 'xmas'], category: 'people', skinToneSupport: true, popularityRank: 82 },
  { emoji: '\u{1F478}', name: 'princess', keywords: ['royalty', 'crown', 'fairy tale'], category: 'people', skinToneSupport: true, popularityRank: 84 },
  { emoji: '\u{1F934}', name: 'prince', keywords: ['royalty', 'crown', 'royal'], category: 'people', skinToneSupport: true, popularityRank: 86 },
  { emoji: '\u{1F470}', name: 'person with veil', keywords: ['bride', 'wedding', 'marriage'], category: 'people', skinToneSupport: true, popularityRank: 88 },
  { emoji: '\u{1F935}', name: 'person in tuxedo', keywords: ['groom', 'wedding', 'formal', 'suit'], category: 'people', skinToneSupport: true, popularityRank: 90 },
  { emoji: '\u{1F47C}', name: 'baby angel', keywords: ['angel', 'cherub', 'cupid'], category: 'people', skinToneSupport: true, popularityRank: 92 },
  { emoji: '\u{1F9D1}', name: 'person', keywords: ['adult', 'person', 'gender neutral'], category: 'people', skinToneSupport: true, popularityRank: 94 },
  { emoji: '\u{1F9D2}', name: 'child', keywords: ['kid', 'young', 'child'], category: 'people', skinToneSupport: true, popularityRank: 96 },
  { emoji: '\u{1F9D3}', name: 'older person', keywords: ['elderly', 'senior', 'old'], category: 'people', skinToneSupport: true, popularityRank: 98 },
  { emoji: '\u{1F9D4}', name: 'person with beard', keywords: ['beard', 'facial hair'], category: 'people', skinToneSupport: true, popularityRank: 100 },
  { emoji: '\u{1F9B8}', name: 'superhero', keywords: ['hero', 'super', 'power', 'cape'], category: 'people', skinToneSupport: true, popularityRank: 102 },
  { emoji: '\u{1F9B9}', name: 'supervillain', keywords: ['villain', 'evil', 'bad'], category: 'people', skinToneSupport: true, popularityRank: 104 },
  { emoji: '\u{1F9D9}', name: 'mage', keywords: ['wizard', 'magic', 'sorcerer'], category: 'people', skinToneSupport: true, popularityRank: 106 },
  { emoji: '\u{1F9DB}', name: 'vampire', keywords: ['dracula', 'undead', 'halloween'], category: 'people', skinToneSupport: true, popularityRank: 108 },
  { emoji: '\u{1F9DC}', name: 'merperson', keywords: ['mermaid', 'merman', 'ocean'], category: 'people', skinToneSupport: true, popularityRank: 110 },
  { emoji: '\u{1F9DA}', name: 'fairy', keywords: ['magic', 'fairy tale', 'wings'], category: 'people', skinToneSupport: true, popularityRank: 112 },
  { emoji: '\u{1F9DE}', name: 'genie', keywords: ['wish', 'magic', 'lamp'], category: 'people', popularityRank: 114 },
  { emoji: '\u{1F9DF}', name: 'zombie', keywords: ['undead', 'walking dead', 'halloween'], category: 'people', popularityRank: 116 },
  { emoji: '\u{1F486}', name: 'person getting massage', keywords: ['spa', 'relax', 'massage'], category: 'people', skinToneSupport: true, popularityRank: 118 },
  { emoji: '\u{1F487}', name: 'person getting haircut', keywords: ['haircut', 'salon', 'barber'], category: 'people', skinToneSupport: true, popularityRank: 120 },
  { emoji: '\u{1F6B6}', name: 'person walking', keywords: ['walk', 'pedestrian', 'stroll'], category: 'people', skinToneSupport: true, popularityRank: 122 },
  { emoji: '\u{1F3C3}', name: 'person running', keywords: ['run', 'sprint', 'jog', 'exercise'], category: 'people', skinToneSupport: true, popularityRank: 124 },
  { emoji: '\u{1F483}', name: 'woman dancing', keywords: ['dance', 'salsa', 'party'], category: 'people', skinToneSupport: true, popularityRank: 126 },
  { emoji: '\u{1F57A}', name: 'man dancing', keywords: ['dance', 'disco', 'party'], category: 'people', skinToneSupport: true, popularityRank: 128 },
  { emoji: '\u{1F46B}', name: 'woman and man holding hands', keywords: ['couple', 'date', 'love', 'together'], category: 'people', popularityRank: 130 },
  { emoji: '\u{1F46D}', name: 'women holding hands', keywords: ['friends', 'couple', 'together'], category: 'people', popularityRank: 132 },
  { emoji: '\u{1F46C}', name: 'men holding hands', keywords: ['friends', 'couple', 'together'], category: 'people', popularityRank: 134 },
  { emoji: '\u{1F48B}', name: 'kiss mark', keywords: ['kiss', 'lips', 'love', 'lipstick'], category: 'people', popularityRank: 136 },
  { emoji: '\u{1F463}', name: 'footprints', keywords: ['feet', 'tracks', 'steps', 'walking'], category: 'people', popularityRank: 138 },
  { emoji: '\u{1F440}', name: 'eyes', keywords: ['look', 'see', 'watch', 'stare'], category: 'people', popularityRank: 140 },
  { emoji: '\u{1F441}\u{FE0F}', name: 'eye', keywords: ['see', 'look', 'vision', 'watch'], category: 'people', popularityRank: 142 },
  { emoji: '\u{1F443}', name: 'nose', keywords: ['smell', 'sniff'], category: 'people', skinToneSupport: true, popularityRank: 144 },
  { emoji: '\u{1F442}', name: 'ear', keywords: ['hear', 'listen', 'sound'], category: 'people', skinToneSupport: true, popularityRank: 146 },
  { emoji: '\u{1F444}', name: 'mouth', keywords: ['lips', 'kiss', 'talk'], category: 'people', popularityRank: 148 },
  { emoji: '\u{1F445}', name: 'tongue', keywords: ['lick', 'taste', 'playful'], category: 'people', popularityRank: 150 },
  { emoji: '\u{1F9E0}', name: 'brain', keywords: ['think', 'smart', 'mind', 'intelligence'], category: 'people', popularityRank: 152 },
  { emoji: '\u{1FAC0}', name: 'anatomical heart', keywords: ['heart', 'organ', 'body'], category: 'people', popularityRank: 154 },
  { emoji: '\u{1F9B4}', name: 'bone', keywords: ['skeleton', 'body', 'anatomy'], category: 'people', popularityRank: 156 },
  { emoji: '\u{1F9B5}', name: 'leg', keywords: ['kick', 'limb', 'body'], category: 'people', skinToneSupport: true, popularityRank: 158 },
  { emoji: '\u{1F9B6}', name: 'foot', keywords: ['kick', 'stomp', 'barefoot'], category: 'people', skinToneSupport: true, popularityRank: 160 },
  { emoji: '\u{1F9B7}', name: 'tooth', keywords: ['dentist', 'teeth', 'bite'], category: 'people', popularityRank: 162 },
  { emoji: '\u{1F485}', name: 'nail polish', keywords: ['beauty', 'manicure', 'nails', 'sassy'], category: 'people', skinToneSupport: true, popularityRank: 164 },
  { emoji: '\u{1F933}', name: 'selfie', keywords: ['camera', 'phone', 'photo', 'selfie'], category: 'people', skinToneSupport: true, popularityRank: 166 },
  { emoji: '\u{1F450}', name: 'open hands', keywords: ['hands', 'open', 'jazz hands'], category: 'people', skinToneSupport: true, popularityRank: 168 },
  { emoji: '\u{1F90F}', name: 'pinching hand', keywords: ['small', 'tiny', 'little', 'pinch'], category: 'people', skinToneSupport: true, popularityRank: 170 },
  { emoji: '\u{1F91B}', name: 'left-facing fist', keywords: ['fist', 'bump', 'left'], category: 'people', skinToneSupport: true, popularityRank: 491 },
  { emoji: '\u{1F91C}', name: 'right-facing fist', keywords: ['fist', 'bump', 'right'], category: 'people', skinToneSupport: true, popularityRank: 492 },
  { emoji: '\u{1F90C}', name: 'pinched fingers', keywords: ['italian', 'gesture', 'what'], category: 'people', skinToneSupport: true, popularityRank: 493 },
  { emoji: '\u{1F91A}', name: 'raised back of hand', keywords: ['hand', 'back', 'wave'], category: 'people', skinToneSupport: true, popularityRank: 494 },
  { emoji: '\u{270B}', name: 'raised hand', keywords: ['hand', 'stop', 'high five', 'halt'], category: 'people', skinToneSupport: true, popularityRank: 495 },
  { emoji: '\u{1F596}', name: 'vulcan salute', keywords: ['spock', 'star trek', 'hand'], category: 'people', skinToneSupport: true, popularityRank: 496 },
];

// ---------------------------------------------------------------------------
// Animals & Nature (~50)
// ---------------------------------------------------------------------------

const animals: EmojiItem[] = [
  { emoji: '\u{1F436}', name: 'dog face', keywords: ['puppy', 'pet', 'dog', 'woof'], category: 'animals', popularityRank: 172 },
  { emoji: '\u{1F431}', name: 'cat face', keywords: ['kitten', 'pet', 'cat', 'meow'], category: 'animals', popularityRank: 174 },
  { emoji: '\u{1F42D}', name: 'mouse face', keywords: ['mouse', 'rodent', 'squeak'], category: 'animals', popularityRank: 176 },
  { emoji: '\u{1F98B}', name: 'butterfly', keywords: ['insect', 'pretty', 'nature', 'flutter'], category: 'animals', popularityRank: 178 },
  { emoji: '\u{1F339}', name: 'rose', keywords: ['flower', 'love', 'romance', 'valentine'], category: 'animals', popularityRank: 180 },
  { emoji: '\u{1F33B}', name: 'sunflower', keywords: ['flower', 'sun', 'yellow', 'nature'], category: 'animals', popularityRank: 182 },
  { emoji: '\u{1F43B}', name: 'bear', keywords: ['animal', 'grizzly', 'teddy'], category: 'animals', popularityRank: 184 },
  { emoji: '\u{1F981}', name: 'lion', keywords: ['king', 'jungle', 'wild', 'cat'], category: 'animals', popularityRank: 186 },
  { emoji: '\u{1F984}', name: 'unicorn', keywords: ['magic', 'fantasy', 'horse', 'mythical'], category: 'animals', popularityRank: 188 },
  { emoji: '\u{1F412}', name: 'monkey', keywords: ['ape', 'primate', 'banana'], category: 'animals', popularityRank: 190 },
  { emoji: '\u{1F435}', name: 'monkey face', keywords: ['monkey', 'ape', 'primate'], category: 'animals', popularityRank: 192 },
  { emoji: '\u{1F437}', name: 'pig face', keywords: ['pig', 'oink', 'farm', 'animal'], category: 'animals', popularityRank: 194 },
  { emoji: '\u{1F430}', name: 'rabbit face', keywords: ['bunny', 'rabbit', 'easter', 'pet'], category: 'animals', popularityRank: 196 },
  { emoji: '\u{1F424}', name: 'baby chick', keywords: ['bird', 'chick', 'chicken', 'cute'], category: 'animals', popularityRank: 198 },
  { emoji: '\u{1F427}', name: 'penguin', keywords: ['bird', 'cold', 'ice', 'arctic'], category: 'animals', popularityRank: 200 },
  { emoji: '\u{1F438}', name: 'frog', keywords: ['toad', 'amphibian', 'kermit'], category: 'animals', popularityRank: 202 },
  { emoji: '\u{1F40D}', name: 'snake', keywords: ['serpent', 'reptile', 'slither'], category: 'animals', popularityRank: 204 },
  { emoji: '\u{1F422}', name: 'turtle', keywords: ['tortoise', 'slow', 'reptile', 'shell'], category: 'animals', popularityRank: 206 },
  { emoji: '\u{1F433}', name: 'spouting whale', keywords: ['whale', 'ocean', 'sea', 'water'], category: 'animals', popularityRank: 208 },
  { emoji: '\u{1F42C}', name: 'dolphin', keywords: ['ocean', 'sea', 'marine', 'flipper'], category: 'animals', popularityRank: 210 },
  { emoji: '\u{1F419}', name: 'octopus', keywords: ['tentacles', 'ocean', 'sea', 'marine'], category: 'animals', popularityRank: 212 },
  { emoji: '\u{1F41D}', name: 'honeybee', keywords: ['bee', 'insect', 'honey', 'buzz'], category: 'animals', popularityRank: 214 },
  { emoji: '\u{1F41E}', name: 'lady beetle', keywords: ['ladybug', 'insect', 'bug', 'luck'], category: 'animals', popularityRank: 216 },
  { emoji: '\u{1F985}', name: 'eagle', keywords: ['bird', 'america', 'freedom', 'raptor'], category: 'animals', popularityRank: 218 },
  { emoji: '\u{1F989}', name: 'owl', keywords: ['bird', 'wise', 'night', 'hoot'], category: 'animals', popularityRank: 220 },
  { emoji: '\u{1F99A}', name: 'peacock', keywords: ['bird', 'colorful', 'feathers'], category: 'animals', popularityRank: 222 },
  { emoji: '\u{1F98A}', name: 'fox', keywords: ['animal', 'wild', 'cunning', 'sly'], category: 'animals', popularityRank: 224 },
  { emoji: '\u{1F43A}', name: 'wolf', keywords: ['animal', 'wild', 'howl'], category: 'animals', popularityRank: 226 },
  { emoji: '\u{1F434}', name: 'horse face', keywords: ['horse', 'pony', 'stallion'], category: 'animals', popularityRank: 228 },
  { emoji: '\u{1F992}', name: 'giraffe', keywords: ['animal', 'tall', 'africa', 'safari'], category: 'animals', popularityRank: 230 },
  { emoji: '\u{1F418}', name: 'elephant', keywords: ['animal', 'big', 'africa', 'trunk'], category: 'animals', popularityRank: 232 },
  { emoji: '\u{1F98D}', name: 'gorilla', keywords: ['ape', 'primate', 'strong', 'kong'], category: 'animals', popularityRank: 234 },
  { emoji: '\u{1F43C}', name: 'panda', keywords: ['bear', 'bamboo', 'cute', 'china'], category: 'animals', popularityRank: 236 },
  { emoji: '\u{1F428}', name: 'koala', keywords: ['animal', 'australia', 'cute', 'bear'], category: 'animals', popularityRank: 238 },
  { emoji: '\u{1F42F}', name: 'tiger face', keywords: ['tiger', 'cat', 'wild', 'stripes'], category: 'animals', popularityRank: 240 },
  { emoji: '\u{1F40A}', name: 'crocodile', keywords: ['alligator', 'reptile', 'croc'], category: 'animals', popularityRank: 242 },
  { emoji: '\u{1F41F}', name: 'fish', keywords: ['sea', 'ocean', 'marine', 'swim'], category: 'animals', popularityRank: 244 },
  { emoji: '\u{1F988}', name: 'shark', keywords: ['fish', 'ocean', 'danger', 'jaws'], category: 'animals', popularityRank: 246 },
  { emoji: '\u{1F40B}', name: 'whale', keywords: ['ocean', 'sea', 'marine', 'big'], category: 'animals', popularityRank: 248 },
  { emoji: '\u{1F33A}', name: 'hibiscus', keywords: ['flower', 'tropical', 'pink', 'nature'], category: 'animals', popularityRank: 250 },
  { emoji: '\u{1F337}', name: 'tulip', keywords: ['flower', 'spring', 'garden', 'nature'], category: 'animals', popularityRank: 252 },
  { emoji: '\u{1F33C}', name: 'blossom', keywords: ['flower', 'daisy', 'nature', 'spring'], category: 'animals', popularityRank: 254 },
  { emoji: '\u{1F332}', name: 'evergreen tree', keywords: ['tree', 'pine', 'nature', 'forest'], category: 'animals', popularityRank: 256 },
  { emoji: '\u{1F333}', name: 'deciduous tree', keywords: ['tree', 'nature', 'forest', 'oak'], category: 'animals', popularityRank: 258 },
  { emoji: '\u{1F335}', name: 'cactus', keywords: ['desert', 'plant', 'prickly', 'nature'], category: 'animals', popularityRank: 260 },
  { emoji: '\u{1F490}', name: 'bouquet', keywords: ['flowers', 'gift', 'romance', 'arrangement'], category: 'animals', popularityRank: 262 },
  { emoji: '\u{1F338}', name: 'cherry blossom', keywords: ['flower', 'spring', 'sakura', 'japan'], category: 'animals', popularityRank: 264 },
  { emoji: '\u{1F334}', name: 'palm tree', keywords: ['tropical', 'beach', 'vacation', 'tree'], category: 'animals', popularityRank: 266 },
  { emoji: '\u{1F340}', name: 'four leaf clover', keywords: ['luck', 'lucky', 'irish', 'clover'], category: 'animals', popularityRank: 268 },
  { emoji: '\u{1F341}', name: 'maple leaf', keywords: ['autumn', 'fall', 'canada', 'leaf'], category: 'animals', popularityRank: 270 },
  { emoji: '\u{1F426}', name: 'bird', keywords: ['fly', 'tweet', 'nature'], category: 'animals', popularityRank: 497 },
  { emoji: '\u{1F40C}', name: 'snail', keywords: ['slow', 'shell', 'slug'], category: 'animals', popularityRank: 498 },
  { emoji: '\u{1F41A}', name: 'spiral shell', keywords: ['shell', 'beach', 'ocean', 'sea'], category: 'animals', popularityRank: 499 },
  { emoji: '\u{1F980}', name: 'crab', keywords: ['lobster', 'ocean', 'seafood', 'cancer'], category: 'animals', popularityRank: 500 },
  { emoji: '\u{1F982}', name: 'scorpion', keywords: ['zodiac', 'sting', 'insect', 'desert'], category: 'animals', popularityRank: 501 },
  { emoji: '\u{1F996}', name: 'T-Rex', keywords: ['dinosaur', 'prehistoric', 'jurassic'], category: 'animals', popularityRank: 502 },
  { emoji: '\u{1F995}', name: 'sauropod', keywords: ['dinosaur', 'brontosaurus', 'prehistoric'], category: 'animals', popularityRank: 503 },
];

// ---------------------------------------------------------------------------
// Food & Drink (~50)
// ---------------------------------------------------------------------------

const food: EmojiItem[] = [
  { emoji: '\u{2615}', name: 'hot beverage', keywords: ['coffee', 'tea', 'hot', 'drink'], category: 'food', popularityRank: 171 },
  { emoji: '\u{1F355}', name: 'pizza', keywords: ['food', 'italian', 'slice', 'cheese'], category: 'food', popularityRank: 173 },
  { emoji: '\u{1F382}', name: 'birthday cake', keywords: ['cake', 'birthday', 'party', 'dessert'], category: 'food', popularityRank: 175 },
  { emoji: '\u{1F37B}', name: 'clinking beer mugs', keywords: ['beer', 'cheers', 'drink', 'toast'], category: 'food', popularityRank: 177 },
  { emoji: '\u{1F370}', name: 'shortcake', keywords: ['cake', 'dessert', 'sweet', 'strawberry'], category: 'food', popularityRank: 179 },
  { emoji: '\u{1F354}', name: 'hamburger', keywords: ['burger', 'food', 'fast food', 'beef'], category: 'food', popularityRank: 181 },
  { emoji: '\u{1F35F}', name: 'french fries', keywords: ['fries', 'chips', 'food', 'fast food'], category: 'food', popularityRank: 183 },
  { emoji: '\u{1F363}', name: 'sushi', keywords: ['japanese', 'food', 'fish', 'rice'], category: 'food', popularityRank: 185 },
  { emoji: '\u{1F36B}', name: 'chocolate bar', keywords: ['candy', 'sweet', 'chocolate', 'snack'], category: 'food', popularityRank: 187 },
  { emoji: '\u{1F366}', name: 'soft ice cream', keywords: ['ice cream', 'dessert', 'sweet', 'cone'], category: 'food', popularityRank: 189 },
  { emoji: '\u{1F369}', name: 'doughnut', keywords: ['donut', 'dessert', 'sweet', 'snack'], category: 'food', popularityRank: 191 },
  { emoji: '\u{1F37A}', name: 'beer mug', keywords: ['beer', 'drink', 'alcohol', 'pub'], category: 'food', popularityRank: 193 },
  { emoji: '\u{1F377}', name: 'wine glass', keywords: ['wine', 'drink', 'alcohol', 'red'], category: 'food', popularityRank: 195 },
  { emoji: '\u{1F378}', name: 'cocktail glass', keywords: ['drink', 'alcohol', 'martini', 'bar'], category: 'food', popularityRank: 197 },
  { emoji: '\u{1F34E}', name: 'red apple', keywords: ['apple', 'fruit', 'healthy', 'food'], category: 'food', popularityRank: 199 },
  { emoji: '\u{1F34A}', name: 'tangerine', keywords: ['orange', 'fruit', 'citrus'], category: 'food', popularityRank: 201 },
  { emoji: '\u{1F34C}', name: 'banana', keywords: ['fruit', 'yellow', 'food', 'monkey'], category: 'food', popularityRank: 203 },
  { emoji: '\u{1F353}', name: 'strawberry', keywords: ['berry', 'fruit', 'red', 'sweet'], category: 'food', popularityRank: 205 },
  { emoji: '\u{1F347}', name: 'grapes', keywords: ['fruit', 'wine', 'purple', 'vine'], category: 'food', popularityRank: 207 },
  { emoji: '\u{1F349}', name: 'watermelon', keywords: ['fruit', 'summer', 'melon', 'juicy'], category: 'food', popularityRank: 209 },
  { emoji: '\u{1F351}', name: 'peach', keywords: ['fruit', 'butt', 'fuzzy', 'sweet'], category: 'food', popularityRank: 211 },
  { emoji: '\u{1F352}', name: 'cherries', keywords: ['fruit', 'cherry', 'red', 'sweet'], category: 'food', popularityRank: 213 },
  { emoji: '\u{1F34D}', name: 'pineapple', keywords: ['fruit', 'tropical', 'sweet'], category: 'food', popularityRank: 215 },
  { emoji: '\u{1F96D}', name: 'mango', keywords: ['fruit', 'tropical', 'sweet'], category: 'food', popularityRank: 217 },
  { emoji: '\u{1F951}', name: 'avocado', keywords: ['fruit', 'guacamole', 'healthy', 'toast'], category: 'food', popularityRank: 219 },
  { emoji: '\u{1F95A}', name: 'egg', keywords: ['breakfast', 'food', 'chicken'], category: 'food', popularityRank: 221 },
  { emoji: '\u{1F953}', name: 'bacon', keywords: ['meat', 'breakfast', 'pork', 'food'], category: 'food', popularityRank: 223 },
  { emoji: '\u{1F32E}', name: 'taco', keywords: ['mexican', 'food', 'tuesday'], category: 'food', popularityRank: 225 },
  { emoji: '\u{1F32F}', name: 'burrito', keywords: ['mexican', 'food', 'wrap'], category: 'food', popularityRank: 227 },
  { emoji: '\u{1F35C}', name: 'steaming bowl', keywords: ['ramen', 'noodles', 'soup', 'pho'], category: 'food', popularityRank: 229 },
  { emoji: '\u{1F357}', name: 'poultry leg', keywords: ['chicken', 'meat', 'food', 'drumstick'], category: 'food', popularityRank: 231 },
  { emoji: '\u{1F356}', name: 'meat on bone', keywords: ['meat', 'food', 'steak', 'bone'], category: 'food', popularityRank: 233 },
  { emoji: '\u{1F36A}', name: 'cookie', keywords: ['biscuit', 'snack', 'sweet', 'dessert'], category: 'food', popularityRank: 235 },
  { emoji: '\u{1F36D}', name: 'lollipop', keywords: ['candy', 'sweet', 'sugar', 'snack'], category: 'food', popularityRank: 237 },
  { emoji: '\u{1F36E}', name: 'custard', keywords: ['dessert', 'pudding', 'sweet', 'flan'], category: 'food', popularityRank: 239 },
  { emoji: '\u{1F36F}', name: 'honey pot', keywords: ['honey', 'sweet', 'bee'], category: 'food', popularityRank: 241 },
  { emoji: '\u{1F379}', name: 'tropical drink', keywords: ['cocktail', 'drink', 'summer', 'beach'], category: 'food', popularityRank: 243 },
  { emoji: '\u{1F375}', name: 'teacup without handle', keywords: ['tea', 'drink', 'green tea', 'matcha'], category: 'food', popularityRank: 245 },
  { emoji: '\u{1F376}', name: 'sake', keywords: ['japanese', 'drink', 'alcohol', 'rice wine'], category: 'food', popularityRank: 247 },
  { emoji: '\u{1F37E}', name: 'bottle with popping cork', keywords: ['champagne', 'celebrate', 'wine', 'party'], category: 'food', popularityRank: 249 },
  { emoji: '\u{1F950}', name: 'croissant', keywords: ['bread', 'french', 'bakery', 'pastry'], category: 'food', popularityRank: 251 },
  { emoji: '\u{1F956}', name: 'baguette bread', keywords: ['bread', 'french', 'food'], category: 'food', popularityRank: 253 },
  { emoji: '\u{1F968}', name: 'pretzel', keywords: ['snack', 'bread', 'twisted'], category: 'food', popularityRank: 255 },
  { emoji: '\u{1F9C0}', name: 'cheese wedge', keywords: ['cheese', 'dairy', 'food'], category: 'food', popularityRank: 257 },
  { emoji: '\u{1F955}', name: 'carrot', keywords: ['vegetable', 'orange', 'food', 'healthy'], category: 'food', popularityRank: 259 },
  { emoji: '\u{1F33D}', name: 'ear of corn', keywords: ['corn', 'vegetable', 'maize', 'food'], category: 'food', popularityRank: 261 },
  { emoji: '\u{1F336}\u{FE0F}', name: 'hot pepper', keywords: ['spicy', 'chili', 'pepper', 'hot'], category: 'food', popularityRank: 263 },
  { emoji: '\u{1F954}', name: 'potato', keywords: ['vegetable', 'food', 'starch', 'fries'], category: 'food', popularityRank: 265 },
  { emoji: '\u{1F96B}', name: 'canned food', keywords: ['can', 'food', 'tin', 'preserved'], category: 'food', popularityRank: 267 },
  { emoji: '\u{1F9C1}', name: 'cupcake', keywords: ['cake', 'dessert', 'sweet', 'muffin'], category: 'food', popularityRank: 269 },
];

// ---------------------------------------------------------------------------
// Travel & Places (~40)
// ---------------------------------------------------------------------------

const travel: EmojiItem[] = [
  { emoji: '\u{2708}\u{FE0F}', name: 'airplane', keywords: ['plane', 'travel', 'flight', 'fly'], category: 'travel', popularityRank: 271 },
  { emoji: '\u{1F30D}', name: 'globe showing europe-africa', keywords: ['earth', 'world', 'globe', 'planet'], category: 'travel', popularityRank: 273 },
  { emoji: '\u{1F3E0}', name: 'house', keywords: ['home', 'building', 'residence'], category: 'travel', popularityRank: 275 },
  { emoji: '\u{1F697}', name: 'automobile', keywords: ['car', 'drive', 'vehicle', 'road'], category: 'travel', popularityRank: 277 },
  { emoji: '\u{2600}\u{FE0F}', name: 'sun', keywords: ['sunny', 'weather', 'bright', 'warm'], category: 'travel', popularityRank: 279 },
  { emoji: '\u{1F319}', name: 'crescent moon', keywords: ['moon', 'night', 'sky', 'sleep'], category: 'travel', popularityRank: 281 },
  { emoji: '\u{2B50}', name: 'star', keywords: ['night', 'sky', 'gold', 'shine'], category: 'travel', popularityRank: 283 },
  { emoji: '\u{1F308}', name: 'rainbow', keywords: ['weather', 'colorful', 'pride', 'sky'], category: 'travel', popularityRank: 285 },
  { emoji: '\u{26A1}', name: 'high voltage', keywords: ['lightning', 'thunder', 'electric', 'power'], category: 'travel', popularityRank: 287 },
  { emoji: '\u{1F30A}', name: 'water wave', keywords: ['ocean', 'wave', 'sea', 'surf'], category: 'travel', popularityRank: 289 },
  { emoji: '\u{1F3D6}\u{FE0F}', name: 'beach with umbrella', keywords: ['beach', 'vacation', 'summer', 'sand'], category: 'travel', popularityRank: 291 },
  { emoji: '\u{1F3D4}\u{FE0F}', name: 'snow-capped mountain', keywords: ['mountain', 'snow', 'winter', 'nature'], category: 'travel', popularityRank: 293 },
  { emoji: '\u{1F680}', name: 'rocket', keywords: ['space', 'launch', 'ship', 'startup'], category: 'travel', popularityRank: 295 },
  { emoji: '\u{1F6F8}', name: 'flying saucer', keywords: ['ufo', 'alien', 'space', 'ship'], category: 'travel', popularityRank: 297 },
  { emoji: '\u{1F695}', name: 'taxi', keywords: ['cab', 'car', 'transport', 'ride'], category: 'travel', popularityRank: 299 },
  { emoji: '\u{1F68C}', name: 'bus', keywords: ['transport', 'vehicle', 'public', 'school'], category: 'travel', popularityRank: 301 },
  { emoji: '\u{1F682}', name: 'locomotive', keywords: ['train', 'railway', 'steam', 'engine'], category: 'travel', popularityRank: 303 },
  { emoji: '\u{1F6A2}', name: 'ship', keywords: ['boat', 'cruise', 'sea', 'ocean'], category: 'travel', popularityRank: 305 },
  { emoji: '\u{1F6B2}', name: 'bicycle', keywords: ['bike', 'cycling', 'ride', 'exercise'], category: 'travel', popularityRank: 307 },
  { emoji: '\u{1F3E2}', name: 'office building', keywords: ['work', 'office', 'building', 'business'], category: 'travel', popularityRank: 309 },
  { emoji: '\u{1F3E5}', name: 'hospital', keywords: ['medical', 'health', 'doctor', 'building'], category: 'travel', popularityRank: 311 },
  { emoji: '\u{1F3EB}', name: 'school', keywords: ['education', 'learning', 'building', 'study'], category: 'travel', popularityRank: 313 },
  { emoji: '\u{26EA}', name: 'church', keywords: ['religion', 'christian', 'worship', 'building'], category: 'travel', popularityRank: 315 },
  { emoji: '\u{1F3F0}', name: 'castle', keywords: ['medieval', 'fortress', 'fairy tale', 'building'], category: 'travel', popularityRank: 317 },
  { emoji: '\u{1F5FD}', name: 'statue of liberty', keywords: ['new york', 'america', 'monument', 'landmark'], category: 'travel', popularityRank: 319 },
  { emoji: '\u{1F5FC}', name: 'tokyo tower', keywords: ['japan', 'tokyo', 'landmark', 'tower'], category: 'travel', popularityRank: 321 },
  { emoji: '\u{1F3DD}\u{FE0F}', name: 'desert island', keywords: ['island', 'tropical', 'beach', 'palm'], category: 'travel', popularityRank: 323 },
  { emoji: '\u{1F3D5}\u{FE0F}', name: 'camping', keywords: ['tent', 'outdoors', 'nature', 'camp'], category: 'travel', popularityRank: 325 },
  { emoji: '\u{26C5}', name: 'sun behind cloud', keywords: ['weather', 'partly cloudy', 'cloud'], category: 'travel', popularityRank: 327 },
  { emoji: '\u{1F327}\u{FE0F}', name: 'cloud with rain', keywords: ['rain', 'weather', 'rainy', 'wet'], category: 'travel', popularityRank: 329 },
  { emoji: '\u{2744}\u{FE0F}', name: 'snowflake', keywords: ['snow', 'cold', 'winter', 'ice'], category: 'travel', popularityRank: 331 },
  { emoji: '\u{1F328}\u{FE0F}', name: 'cloud with snow', keywords: ['snow', 'weather', 'winter', 'cold'], category: 'travel', popularityRank: 333 },
  { emoji: '\u{1F30B}', name: 'volcano', keywords: ['eruption', 'lava', 'mountain', 'disaster'], category: 'travel', popularityRank: 335 },
  { emoji: '\u{1F3DC}\u{FE0F}', name: 'desert', keywords: ['sand', 'dry', 'hot', 'arid'], category: 'travel', popularityRank: 337 },
  { emoji: '\u{1F5FA}\u{FE0F}', name: 'world map', keywords: ['map', 'globe', 'travel', 'geography'], category: 'travel', popularityRank: 339 },
  { emoji: '\u{1F9ED}', name: 'compass', keywords: ['navigation', 'direction', 'travel', 'explore'], category: 'travel', popularityRank: 341 },
  { emoji: '\u{1F30C}', name: 'milky way', keywords: ['galaxy', 'space', 'stars', 'night'], category: 'travel', popularityRank: 343 },
  { emoji: '\u{1F3A0}', name: 'carousel horse', keywords: ['amusement', 'ride', 'park', 'horse'], category: 'travel', popularityRank: 345 },
  { emoji: '\u{1F3A1}', name: 'ferris wheel', keywords: ['amusement', 'ride', 'park', 'carnival'], category: 'travel', popularityRank: 347 },
  { emoji: '\u{1F3A2}', name: 'roller coaster', keywords: ['amusement', 'ride', 'theme park', 'fun'], category: 'travel', popularityRank: 349 },
];

// ---------------------------------------------------------------------------
// Activities (~40)
// ---------------------------------------------------------------------------

const activities: EmojiItem[] = [
  { emoji: '\u{26BD}', name: 'soccer ball', keywords: ['football', 'soccer', 'sport', 'ball'], category: 'activities', popularityRank: 272 },
  { emoji: '\u{1F3C0}', name: 'basketball', keywords: ['sport', 'ball', 'hoop', 'nba'], category: 'activities', popularityRank: 274 },
  { emoji: '\u{1F3C8}', name: 'american football', keywords: ['sport', 'football', 'nfl', 'ball'], category: 'activities', popularityRank: 276 },
  { emoji: '\u{26BE}', name: 'baseball', keywords: ['sport', 'ball', 'mlb'], category: 'activities', popularityRank: 278 },
  { emoji: '\u{1F3BE}', name: 'tennis', keywords: ['sport', 'ball', 'racket', 'court'], category: 'activities', popularityRank: 280 },
  { emoji: '\u{1F3B5}', name: 'musical note', keywords: ['music', 'song', 'melody', 'tune'], category: 'activities', popularityRank: 282 },
  { emoji: '\u{1F3B6}', name: 'musical notes', keywords: ['music', 'song', 'melody', 'singing'], category: 'activities', popularityRank: 284 },
  { emoji: '\u{1F3B8}', name: 'guitar', keywords: ['music', 'instrument', 'rock', 'play'], category: 'activities', popularityRank: 286 },
  { emoji: '\u{1F3A4}', name: 'microphone', keywords: ['karaoke', 'sing', 'music', 'mic'], category: 'activities', popularityRank: 288 },
  { emoji: '\u{1F3AC}', name: 'clapper board', keywords: ['movie', 'film', 'cinema', 'action'], category: 'activities', popularityRank: 290 },
  { emoji: '\u{1F3AE}', name: 'video game', keywords: ['game', 'controller', 'play', 'gaming'], category: 'activities', popularityRank: 292 },
  { emoji: '\u{1F381}', name: 'wrapped gift', keywords: ['present', 'gift', 'birthday', 'christmas'], category: 'activities', popularityRank: 294 },
  { emoji: '\u{1F389}', name: 'party popper', keywords: ['party', 'celebrate', 'confetti', 'hooray'], category: 'activities', popularityRank: 296 },
  { emoji: '\u{1F38A}', name: 'confetti ball', keywords: ['party', 'celebrate', 'festival'], category: 'activities', popularityRank: 298 },
  { emoji: '\u{1F3C6}', name: 'trophy', keywords: ['winner', 'champion', 'award', 'prize'], category: 'activities', popularityRank: 300 },
  { emoji: '\u{1F3C5}', name: 'sports medal', keywords: ['medal', 'award', 'winner', 'gold'], category: 'activities', popularityRank: 302 },
  { emoji: '\u{1F947}', name: 'first place medal', keywords: ['gold', 'winner', 'champion', 'award'], category: 'activities', popularityRank: 304 },
  { emoji: '\u{1F948}', name: 'second place medal', keywords: ['silver', 'runner up', 'award'], category: 'activities', popularityRank: 306 },
  { emoji: '\u{1F949}', name: 'third place medal', keywords: ['bronze', 'award', 'third'], category: 'activities', popularityRank: 308 },
  { emoji: '\u{1F3AF}', name: 'bullseye', keywords: ['target', 'dart', 'aim', 'goal'], category: 'activities', popularityRank: 310 },
  { emoji: '\u{1F3B3}', name: 'bowling', keywords: ['sport', 'strike', 'pin', 'ball'], category: 'activities', popularityRank: 312 },
  { emoji: '\u{1F3D3}', name: 'ping pong', keywords: ['table tennis', 'sport', 'paddle'], category: 'activities', popularityRank: 314 },
  { emoji: '\u{1F94A}', name: 'boxing glove', keywords: ['boxing', 'fight', 'sport', 'punch'], category: 'activities', popularityRank: 316 },
  { emoji: '\u{1F3CB}\u{FE0F}', name: 'person lifting weights', keywords: ['gym', 'fitness', 'exercise', 'strong'], category: 'activities', popularityRank: 318 },
  { emoji: '\u{1F3CA}', name: 'person swimming', keywords: ['swim', 'pool', 'sport', 'water'], category: 'activities', popularityRank: 320 },
  { emoji: '\u{1F3BF}', name: 'skis', keywords: ['ski', 'snow', 'winter', 'sport'], category: 'activities', popularityRank: 322 },
  { emoji: '\u{1F3A8}', name: 'artist palette', keywords: ['art', 'paint', 'draw', 'color'], category: 'activities', popularityRank: 324 },
  { emoji: '\u{1F3AD}', name: 'performing arts', keywords: ['theater', 'drama', 'masks', 'acting'], category: 'activities', popularityRank: 326 },
  { emoji: '\u{265F}\u{FE0F}', name: 'chess pawn', keywords: ['chess', 'game', 'strategy', 'board'], category: 'activities', popularityRank: 328 },
  { emoji: '\u{1F3B2}', name: 'game die', keywords: ['dice', 'game', 'random', 'chance'], category: 'activities', popularityRank: 330 },
  { emoji: '\u{1F9E9}', name: 'puzzle piece', keywords: ['puzzle', 'jigsaw', 'solve', 'piece'], category: 'activities', popularityRank: 332 },
  { emoji: '\u{1FA81}', name: 'kite', keywords: ['fly', 'wind', 'outdoor', 'toy'], category: 'activities', popularityRank: 334 },
  { emoji: '\u{1F3AA}', name: 'circus tent', keywords: ['circus', 'carnival', 'show', 'tent'], category: 'activities', popularityRank: 336 },
  { emoji: '\u{1F3B9}', name: 'musical keyboard', keywords: ['piano', 'music', 'keys', 'instrument'], category: 'activities', popularityRank: 338 },
  { emoji: '\u{1F941}', name: 'drum', keywords: ['music', 'instrument', 'beat', 'percussion'], category: 'activities', popularityRank: 340 },
  { emoji: '\u{1F3BB}', name: 'violin', keywords: ['music', 'instrument', 'classical', 'fiddle'], category: 'activities', popularityRank: 342 },
  { emoji: '\u{1F3BA}', name: 'trumpet', keywords: ['music', 'instrument', 'brass', 'horn'], category: 'activities', popularityRank: 344 },
  { emoji: '\u{1F3B7}', name: 'saxophone', keywords: ['music', 'instrument', 'jazz', 'sax'], category: 'activities', popularityRank: 346 },
  { emoji: '\u{1FA80}', name: 'yo-yo', keywords: ['toy', 'play', 'string'], category: 'activities', popularityRank: 348 },
  { emoji: '\u{1F3AB}', name: 'ticket', keywords: ['event', 'admission', 'concert', 'movie'], category: 'activities', popularityRank: 350 },
  { emoji: '\u{1F9D8}', name: 'person in lotus position', keywords: ['yoga', 'meditation', 'zen', 'calm'], category: 'activities', popularityRank: 515 },
  { emoji: '\u{1F6B5}', name: 'person mountain biking', keywords: ['bike', 'cycling', 'mountain', 'sport'], category: 'activities', popularityRank: 516 },
  { emoji: '\u{1F3C4}', name: 'person surfing', keywords: ['surf', 'wave', 'ocean', 'sport'], category: 'activities', popularityRank: 517 },
  { emoji: '\u{1F938}', name: 'person cartwheeling', keywords: ['gymnastics', 'cartwheel', 'acrobat'], category: 'activities', popularityRank: 518 },
  { emoji: '\u{1F3CC}\u{FE0F}', name: 'person golfing', keywords: ['golf', 'sport', 'club'], category: 'activities', popularityRank: 519 },
  { emoji: '\u{1F3B0}', name: 'slot machine', keywords: ['gamble', 'casino', 'luck', 'jackpot'], category: 'activities', popularityRank: 520 },
];

// ---------------------------------------------------------------------------
// Objects (~60)
// ---------------------------------------------------------------------------

const objects: EmojiItem[] = [
  { emoji: '\u{1F4F1}', name: 'mobile phone', keywords: ['phone', 'cell', 'smartphone', 'call'], category: 'objects', popularityRank: 351 },
  { emoji: '\u{1F4BB}', name: 'laptop', keywords: ['computer', 'pc', 'work', 'macbook'], category: 'objects', popularityRank: 353 },
  { emoji: '\u{1F4F7}', name: 'camera', keywords: ['photo', 'picture', 'photography'], category: 'objects', popularityRank: 355 },
  { emoji: '\u{1F4A1}', name: 'light bulb', keywords: ['idea', 'light', 'bright', 'lamp'], category: 'objects', popularityRank: 357 },
  { emoji: '\u{1F4DA}', name: 'books', keywords: ['book', 'read', 'library', 'study'], category: 'objects', popularityRank: 359 },
  { emoji: '\u{270F}\u{FE0F}', name: 'pencil', keywords: ['write', 'draw', 'edit', 'school'], category: 'objects', popularityRank: 361 },
  { emoji: '\u{1F4E7}', name: 'e-mail', keywords: ['email', 'mail', 'message', 'inbox'], category: 'objects', popularityRank: 363 },
  { emoji: '\u{1F4B0}', name: 'money bag', keywords: ['money', 'cash', 'rich', 'dollar'], category: 'objects', popularityRank: 365 },
  { emoji: '\u{1F48E}', name: 'gem stone', keywords: ['diamond', 'jewel', 'gem', 'precious'], category: 'objects', popularityRank: 367 },
  { emoji: '\u{1F4E3}', name: 'megaphone', keywords: ['announcement', 'loud', 'speaker', 'shout'], category: 'objects', popularityRank: 369 },
  { emoji: '\u{1F514}', name: 'bell', keywords: ['notification', 'ring', 'alarm', 'alert'], category: 'objects', popularityRank: 371 },
  { emoji: '\u{1F50D}', name: 'magnifying glass tilted left', keywords: ['search', 'find', 'zoom', 'look'], category: 'objects', popularityRank: 373 },
  { emoji: '\u{1F512}', name: 'locked', keywords: ['lock', 'secure', 'password', 'private'], category: 'objects', popularityRank: 375 },
  { emoji: '\u{1F513}', name: 'unlocked', keywords: ['unlock', 'open', 'access'], category: 'objects', popularityRank: 377 },
  { emoji: '\u{1F511}', name: 'key', keywords: ['lock', 'password', 'access', 'unlock'], category: 'objects', popularityRank: 379 },
  { emoji: '\u{1F528}', name: 'hammer', keywords: ['tool', 'build', 'fix', 'construct'], category: 'objects', popularityRank: 381 },
  { emoji: '\u{1F527}', name: 'wrench', keywords: ['tool', 'fix', 'repair', 'settings'], category: 'objects', popularityRank: 383 },
  { emoji: '\u{2699}\u{FE0F}', name: 'gear', keywords: ['settings', 'cog', 'mechanical', 'config'], category: 'objects', popularityRank: 385 },
  { emoji: '\u{1F4A3}', name: 'bomb', keywords: ['explosive', 'danger', 'boom'], category: 'objects', popularityRank: 387 },
  { emoji: '\u{1F52B}', name: 'water pistol', keywords: ['gun', 'squirt', 'toy', 'water'], category: 'objects', popularityRank: 389 },
  { emoji: '\u{1F4F0}', name: 'newspaper', keywords: ['news', 'paper', 'media', 'press'], category: 'objects', popularityRank: 391 },
  { emoji: '\u{1F4AC}', name: 'speech balloon', keywords: ['chat', 'message', 'talk', 'bubble'], category: 'objects', popularityRank: 393 },
  { emoji: '\u{1F4AD}', name: 'thought balloon', keywords: ['think', 'thought', 'bubble', 'wonder'], category: 'objects', popularityRank: 395 },
  { emoji: '\u{1F4CC}', name: 'pushpin', keywords: ['pin', 'location', 'mark', 'note'], category: 'objects', popularityRank: 397 },
  { emoji: '\u{1F4CE}', name: 'paperclip', keywords: ['clip', 'attach', 'office'], category: 'objects', popularityRank: 399 },
  { emoji: '\u{1F4CB}', name: 'clipboard', keywords: ['paste', 'copy', 'list', 'notes'], category: 'objects', popularityRank: 401 },
  { emoji: '\u{1F4C5}', name: 'calendar', keywords: ['date', 'schedule', 'event', 'planner'], category: 'objects', popularityRank: 403 },
  { emoji: '\u{1F4CA}', name: 'bar chart', keywords: ['chart', 'graph', 'data', 'analytics'], category: 'objects', popularityRank: 405 },
  { emoji: '\u{1F4C8}', name: 'chart increasing', keywords: ['growth', 'trend', 'up', 'stonks'], category: 'objects', popularityRank: 407 },
  { emoji: '\u{1F4C9}', name: 'chart decreasing', keywords: ['down', 'decline', 'trend', 'loss'], category: 'objects', popularityRank: 409 },
  { emoji: '\u{1F4DD}', name: 'memo', keywords: ['note', 'write', 'document', 'pencil'], category: 'objects', popularityRank: 411 },
  { emoji: '\u{1F4D6}', name: 'open book', keywords: ['book', 'read', 'study', 'learn'], category: 'objects', popularityRank: 413 },
  { emoji: '\u{1F4D3}', name: 'notebook', keywords: ['journal', 'diary', 'notes', 'write'], category: 'objects', popularityRank: 415 },
  { emoji: '\u{1F4E6}', name: 'package', keywords: ['box', 'delivery', 'shipping', 'parcel'], category: 'objects', popularityRank: 417 },
  { emoji: '\u{1F4E8}', name: 'incoming envelope', keywords: ['email', 'inbox', 'letter', 'mail'], category: 'objects', popularityRank: 419 },
  { emoji: '\u{1F3F7}\u{FE0F}', name: 'label', keywords: ['tag', 'price', 'name', 'label'], category: 'objects', popularityRank: 421 },
  { emoji: '\u{1F50E}', name: 'magnifying glass tilted right', keywords: ['search', 'find', 'zoom', 'inspect'], category: 'objects', popularityRank: 423 },
  { emoji: '\u{1F56F}\u{FE0F}', name: 'candle', keywords: ['light', 'fire', 'flame', 'romantic'], category: 'objects', popularityRank: 425 },
  { emoji: '\u{1F4A4}', name: 'zzz', keywords: ['sleep', 'tired', 'snore', 'rest'], category: 'objects', popularityRank: 427 },
  { emoji: '\u{1F4AB}', name: 'dizzy', keywords: ['star', 'sparkle', 'daze'], category: 'objects', popularityRank: 429 },
  { emoji: '\u{1F4AF}', name: 'hundred points', keywords: ['100', 'perfect', 'score', 'full'], category: 'objects', popularityRank: 431 },
  { emoji: '\u{1F4B5}', name: 'dollar banknote', keywords: ['money', 'cash', 'dollar', 'bill'], category: 'objects', popularityRank: 433 },
  { emoji: '\u{1F4B3}', name: 'credit card', keywords: ['card', 'payment', 'money', 'bank'], category: 'objects', popularityRank: 435 },
  { emoji: '\u{1F4E9}', name: 'envelope with arrow', keywords: ['email', 'send', 'outbox', 'mail'], category: 'objects', popularityRank: 437 },
  { emoji: '\u{1F4EE}', name: 'postbox', keywords: ['mailbox', 'mail', 'letter', 'post'], category: 'objects', popularityRank: 439 },
  { emoji: '\u{1F50C}', name: 'electric plug', keywords: ['plug', 'power', 'electricity', 'charge'], category: 'objects', popularityRank: 441 },
  { emoji: '\u{1F50B}', name: 'battery', keywords: ['power', 'energy', 'charge', 'electric'], category: 'objects', popularityRank: 443 },
  { emoji: '\u{1F4FA}', name: 'television', keywords: ['tv', 'screen', 'watch', 'show'], category: 'objects', popularityRank: 445 },
  { emoji: '\u{1F4FD}\u{FE0F}', name: 'film projector', keywords: ['movie', 'cinema', 'film', 'projector'], category: 'objects', popularityRank: 447 },
  { emoji: '\u{1F4BF}', name: 'optical disk', keywords: ['cd', 'dvd', 'disk', 'music'], category: 'objects', popularityRank: 449 },
  { emoji: '\u{1F4BE}', name: 'floppy disk', keywords: ['save', 'disk', 'retro', 'storage'], category: 'objects', popularityRank: 451 },
  { emoji: '\u{1F5A8}\u{FE0F}', name: 'printer', keywords: ['print', 'paper', 'office'], category: 'objects', popularityRank: 453 },
  { emoji: '\u{2328}\u{FE0F}', name: 'keyboard', keywords: ['type', 'computer', 'keys', 'input'], category: 'objects', popularityRank: 455 },
  { emoji: '\u{1F5B1}\u{FE0F}', name: 'computer mouse', keywords: ['click', 'cursor', 'pointer'], category: 'objects', popularityRank: 457 },
  { emoji: '\u{1F52D}', name: 'telescope', keywords: ['astronomy', 'space', 'stars', 'observe'], category: 'objects', popularityRank: 459 },
  { emoji: '\u{1F52C}', name: 'microscope', keywords: ['science', 'lab', 'biology', 'research'], category: 'objects', popularityRank: 461 },
  { emoji: '\u{1F9F2}', name: 'magnet', keywords: ['attract', 'magnetic', 'pull'], category: 'objects', popularityRank: 463 },
  { emoji: '\u{1FA9C}', name: 'ladder', keywords: ['climb', 'stairs', 'up', 'tool'], category: 'objects', popularityRank: 465 },
  { emoji: '\u{1F9F9}', name: 'broom', keywords: ['sweep', 'clean', 'witch'], category: 'objects', popularityRank: 467 },
  { emoji: '\u{1F9F4}', name: 'lotion bottle', keywords: ['lotion', 'cream', 'moisturizer'], category: 'objects', popularityRank: 469 },
  { emoji: '\u{1F4F2}', name: 'mobile phone with arrow', keywords: ['phone', 'incoming', 'call', 'receive'], category: 'objects', popularityRank: 504 },
  { emoji: '\u{1F4DE}', name: 'telephone receiver', keywords: ['phone', 'call', 'talk', 'dial'], category: 'objects', popularityRank: 505 },
  { emoji: '\u{1F50A}', name: 'speaker high volume', keywords: ['loud', 'sound', 'volume', 'audio'], category: 'objects', popularityRank: 506 },
  { emoji: '\u{1F507}', name: 'muted speaker', keywords: ['mute', 'silent', 'quiet', 'no sound'], category: 'objects', popularityRank: 507 },
  { emoji: '\u{23F0}', name: 'alarm clock', keywords: ['clock', 'alarm', 'wake up', 'time'], category: 'objects', popularityRank: 508 },
  { emoji: '\u{23F3}', name: 'hourglass not done', keywords: ['time', 'wait', 'loading', 'sand'], category: 'objects', popularityRank: 509 },
  { emoji: '\u{231A}', name: 'watch', keywords: ['time', 'clock', 'wrist'], category: 'objects', popularityRank: 510 },
  { emoji: '\u{1F4A2}', name: 'anger symbol', keywords: ['angry', 'mad', 'comic'], category: 'objects', popularityRank: 511 },
  { emoji: '\u{1F48A}', name: 'pill', keywords: ['medicine', 'drug', 'health', 'pharmacy'], category: 'objects', popularityRank: 512 },
  { emoji: '\u{1FA79}', name: 'adhesive bandage', keywords: ['bandaid', 'heal', 'wound', 'injury'], category: 'objects', popularityRank: 513 },
  { emoji: '\u{1F489}', name: 'syringe', keywords: ['needle', 'vaccine', 'shot', 'medical'], category: 'objects', popularityRank: 514 },
];

// ---------------------------------------------------------------------------
// Symbols (~40)
// ---------------------------------------------------------------------------

const symbols: EmojiItem[] = [
  { emoji: '\u{2705}', name: 'check mark button', keywords: ['check', 'done', 'complete', 'yes'], category: 'symbols', popularityRank: 352 },
  { emoji: '\u{274C}', name: 'cross mark', keywords: ['no', 'wrong', 'delete', 'remove'], category: 'symbols', popularityRank: 354 },
  { emoji: '\u{2714}\u{FE0F}', name: 'check mark', keywords: ['check', 'done', 'correct', 'yes'], category: 'symbols', popularityRank: 356 },
  { emoji: '\u{2728}', name: 'sparkles', keywords: ['stars', 'shine', 'glitter', 'magic'], category: 'symbols', popularityRank: 358 },
  { emoji: '\u{1F4A5}', name: 'collision', keywords: ['boom', 'crash', 'explosion', 'bang'], category: 'symbols', popularityRank: 360 },
  { emoji: '\u{2757}', name: 'red exclamation mark', keywords: ['exclamation', 'important', 'urgent', 'alert'], category: 'symbols', popularityRank: 362 },
  { emoji: '\u{2753}', name: 'red question mark', keywords: ['question', 'what', 'confused', 'ask'], category: 'symbols', popularityRank: 364 },
  { emoji: '\u{1F534}', name: 'red circle', keywords: ['red', 'circle', 'dot', 'stop'], category: 'symbols', popularityRank: 366 },
  { emoji: '\u{1F535}', name: 'blue circle', keywords: ['blue', 'circle', 'dot'], category: 'symbols', popularityRank: 368 },
  { emoji: '\u{1F7E2}', name: 'green circle', keywords: ['green', 'circle', 'dot', 'go'], category: 'symbols', popularityRank: 370 },
  { emoji: '\u{1F7E1}', name: 'yellow circle', keywords: ['yellow', 'circle', 'dot', 'caution'], category: 'symbols', popularityRank: 372 },
  { emoji: '\u{1F49C}', name: 'purple heart', keywords: ['love', 'purple', 'heart'], category: 'symbols', popularityRank: 374 },
  { emoji: '\u{1F499}', name: 'blue heart', keywords: ['love', 'blue', 'heart'], category: 'symbols', popularityRank: 376 },
  { emoji: '\u{1F49A}', name: 'green heart', keywords: ['love', 'green', 'heart'], category: 'symbols', popularityRank: 378 },
  { emoji: '\u{1F49B}', name: 'yellow heart', keywords: ['love', 'yellow', 'heart'], category: 'symbols', popularityRank: 380 },
  { emoji: '\u{1F9E1}', name: 'orange heart', keywords: ['love', 'orange', 'heart'], category: 'symbols', popularityRank: 382 },
  { emoji: '\u{1F5A4}', name: 'black heart', keywords: ['love', 'dark', 'heart', 'emo'], category: 'symbols', popularityRank: 384 },
  { emoji: '\u{1F90D}', name: 'white heart', keywords: ['love', 'white', 'heart', 'pure'], category: 'symbols', popularityRank: 386 },
  { emoji: '\u{1F494}', name: 'broken heart', keywords: ['heartbreak', 'sad', 'love', 'breakup'], category: 'symbols', popularityRank: 388 },
  { emoji: '\u{1F495}', name: 'two hearts', keywords: ['love', 'hearts', 'romance', 'couple'], category: 'symbols', popularityRank: 390 },
  { emoji: '\u{1F496}', name: 'sparkling heart', keywords: ['love', 'sparkle', 'heart', 'shine'], category: 'symbols', popularityRank: 392 },
  { emoji: '\u{1F497}', name: 'growing heart', keywords: ['love', 'heart', 'growing', 'bigger'], category: 'symbols', popularityRank: 394 },
  { emoji: '\u{1F498}', name: 'heart with arrow', keywords: ['love', 'cupid', 'valentine', 'romance'], category: 'symbols', popularityRank: 396 },
  { emoji: '\u{1F493}', name: 'beating heart', keywords: ['love', 'heartbeat', 'pulse', 'alive'], category: 'symbols', popularityRank: 398 },
  { emoji: '\u{267B}\u{FE0F}', name: 'recycling symbol', keywords: ['recycle', 'green', 'eco', 'environment'], category: 'symbols', popularityRank: 400 },
  { emoji: '\u{269B}\u{FE0F}', name: 'atom symbol', keywords: ['atom', 'science', 'physics', 'nuclear'], category: 'symbols', popularityRank: 402 },
  { emoji: '\u{262E}\u{FE0F}', name: 'peace symbol', keywords: ['peace', 'hippie', 'love'], category: 'symbols', popularityRank: 404 },
  { emoji: '\u{267E}\u{FE0F}', name: 'infinity', keywords: ['forever', 'endless', 'loop', 'unlimited'], category: 'symbols', popularityRank: 406 },
  { emoji: '\u{2B06}\u{FE0F}', name: 'up arrow', keywords: ['arrow', 'up', 'direction', 'north'], category: 'symbols', popularityRank: 408 },
  { emoji: '\u{2B07}\u{FE0F}', name: 'down arrow', keywords: ['arrow', 'down', 'direction', 'south'], category: 'symbols', popularityRank: 410 },
  { emoji: '\u{27A1}\u{FE0F}', name: 'right arrow', keywords: ['arrow', 'right', 'direction', 'east'], category: 'symbols', popularityRank: 412 },
  { emoji: '\u{2B05}\u{FE0F}', name: 'left arrow', keywords: ['arrow', 'left', 'direction', 'west'], category: 'symbols', popularityRank: 414 },
  { emoji: '\u{1F504}', name: 'counterclockwise arrows', keywords: ['refresh', 'reload', 'sync', 'rotate'], category: 'symbols', popularityRank: 416 },
  { emoji: '\u{1F503}', name: 'clockwise vertical arrows', keywords: ['reload', 'refresh', 'sync'], category: 'symbols', popularityRank: 418 },
  { emoji: '\u{26A0}\u{FE0F}', name: 'warning', keywords: ['caution', 'alert', 'danger', 'hazard'], category: 'symbols', popularityRank: 420 },
  { emoji: '\u{1F6AB}', name: 'prohibited', keywords: ['no', 'forbidden', 'ban', 'stop'], category: 'symbols', popularityRank: 422 },
  { emoji: '\u{2139}\u{FE0F}', name: 'information', keywords: ['info', 'help', 'about', 'details'], category: 'symbols', popularityRank: 424 },
  { emoji: '\u{1F195}', name: 'new button', keywords: ['new', 'fresh', 'badge'], category: 'symbols', popularityRank: 426 },
  { emoji: '\u{1F198}', name: 'sos button', keywords: ['help', 'emergency', 'sos', 'urgent'], category: 'symbols', popularityRank: 428 },
  { emoji: '\u{1F4F4}', name: 'mobile phone off', keywords: ['mute', 'silent', 'quiet', 'phone'], category: 'symbols', popularityRank: 430 },
  { emoji: '\u{2795}', name: 'plus', keywords: ['add', 'plus', 'more', 'positive'], category: 'symbols', popularityRank: 521 },
  { emoji: '\u{2796}', name: 'minus', keywords: ['subtract', 'minus', 'less', 'negative'], category: 'symbols', popularityRank: 522 },
  { emoji: '\u{2716}\u{FE0F}', name: 'multiply', keywords: ['times', 'multiply', 'x', 'cross'], category: 'symbols', popularityRank: 523 },
  { emoji: '\u{00A9}\u{FE0F}', name: 'copyright', keywords: ['copyright', 'ip', 'legal'], category: 'symbols', popularityRank: 524 },
  { emoji: '\u{00AE}\u{FE0F}', name: 'registered', keywords: ['registered', 'trademark', 'legal'], category: 'symbols', popularityRank: 525 },
  { emoji: '\u{2122}\u{FE0F}', name: 'trade mark', keywords: ['trademark', 'brand', 'legal', 'tm'], category: 'symbols', popularityRank: 526 },
];

// ---------------------------------------------------------------------------
// Flags (~30)
// ---------------------------------------------------------------------------

const flags: EmojiItem[] = [
  { emoji: '\u{1F3F3}\u{FE0F}', name: 'white flag', keywords: ['surrender', 'peace', 'truce'], category: 'flags', popularityRank: 432 },
  { emoji: '\u{1F3F4}', name: 'black flag', keywords: ['flag', 'waving', 'dark'], category: 'flags', popularityRank: 434 },
  { emoji: '\u{1F6A9}', name: 'triangular flag', keywords: ['red flag', 'warning', 'mark'], category: 'flags', popularityRank: 436 },
  { emoji: '\u{1F3C1}', name: 'chequered flag', keywords: ['race', 'finish', 'racing', 'checkered'], category: 'flags', popularityRank: 438 },
  { emoji: '\u{1F38C}', name: 'crossed flags', keywords: ['celebration', 'japan', 'flags'], category: 'flags', popularityRank: 440 },
  { emoji: '\u{1F3F4}\u200D\u2620\u{FE0F}', name: 'pirate flag', keywords: ['pirate', 'skull', 'crossbones', 'jolly roger'], category: 'flags', popularityRank: 442 },
  { emoji: '\u{1F1FA}\u{1F1F8}', name: 'flag united states', keywords: ['usa', 'america', 'us'], category: 'flags', popularityRank: 444 },
  { emoji: '\u{1F1EC}\u{1F1E7}', name: 'flag united kingdom', keywords: ['uk', 'britain', 'england'], category: 'flags', popularityRank: 446 },
  { emoji: '\u{1F1E8}\u{1F1E6}', name: 'flag canada', keywords: ['canada', 'maple'], category: 'flags', popularityRank: 448 },
  { emoji: '\u{1F1E6}\u{1F1FA}', name: 'flag australia', keywords: ['australia', 'aussie'], category: 'flags', popularityRank: 450 },
  { emoji: '\u{1F1EB}\u{1F1F7}', name: 'flag france', keywords: ['france', 'french'], category: 'flags', popularityRank: 452 },
  { emoji: '\u{1F1E9}\u{1F1EA}', name: 'flag germany', keywords: ['germany', 'german'], category: 'flags', popularityRank: 454 },
  { emoji: '\u{1F1EF}\u{1F1F5}', name: 'flag japan', keywords: ['japan', 'japanese'], category: 'flags', popularityRank: 456 },
  { emoji: '\u{1F1F0}\u{1F1F7}', name: 'flag south korea', keywords: ['korea', 'korean'], category: 'flags', popularityRank: 458 },
  { emoji: '\u{1F1E8}\u{1F1F3}', name: 'flag china', keywords: ['china', 'chinese'], category: 'flags', popularityRank: 460 },
  { emoji: '\u{1F1EE}\u{1F1F3}', name: 'flag india', keywords: ['india', 'indian'], category: 'flags', popularityRank: 462 },
  { emoji: '\u{1F1E7}\u{1F1F7}', name: 'flag brazil', keywords: ['brazil', 'brazilian'], category: 'flags', popularityRank: 464 },
  { emoji: '\u{1F1F2}\u{1F1FD}', name: 'flag mexico', keywords: ['mexico', 'mexican'], category: 'flags', popularityRank: 466 },
  { emoji: '\u{1F1EA}\u{1F1F8}', name: 'flag spain', keywords: ['spain', 'spanish'], category: 'flags', popularityRank: 468 },
  { emoji: '\u{1F1EE}\u{1F1F9}', name: 'flag italy', keywords: ['italy', 'italian'], category: 'flags', popularityRank: 470 },
  { emoji: '\u{1F1F7}\u{1F1FA}', name: 'flag russia', keywords: ['russia', 'russian'], category: 'flags', popularityRank: 472 },
  { emoji: '\u{1F1F8}\u{1F1EA}', name: 'flag sweden', keywords: ['sweden', 'swedish'], category: 'flags', popularityRank: 474 },
  { emoji: '\u{1F1F3}\u{1F1F4}', name: 'flag norway', keywords: ['norway', 'norwegian'], category: 'flags', popularityRank: 476 },
  { emoji: '\u{1F1F3}\u{1F1FF}', name: 'flag new zealand', keywords: ['new zealand', 'kiwi'], category: 'flags', popularityRank: 478 },
  { emoji: '\u{1F1F8}\u{1F1EC}', name: 'flag singapore', keywords: ['singapore'], category: 'flags', popularityRank: 480 },
  { emoji: '\u{1F1FF}\u{1F1E6}', name: 'flag south africa', keywords: ['south africa'], category: 'flags', popularityRank: 482 },
  { emoji: '\u{1F1F5}\u{1F1F9}', name: 'flag portugal', keywords: ['portugal', 'portuguese'], category: 'flags', popularityRank: 484 },
  { emoji: '\u{1F1E6}\u{1F1F7}', name: 'flag argentina', keywords: ['argentina', 'argentinian'], category: 'flags', popularityRank: 486 },
  { emoji: '\u{1F1F3}\u{1F1EC}', name: 'flag nigeria', keywords: ['nigeria', 'nigerian'], category: 'flags', popularityRank: 488 },
  { emoji: '\u{1F1EA}\u{1F1EC}', name: 'flag egypt', keywords: ['egypt', 'egyptian'], category: 'flags', popularityRank: 490 },
  { emoji: '\u{1F1F9}\u{1F1ED}', name: 'flag thailand', keywords: ['thailand', 'thai'], category: 'flags', popularityRank: 527 },
  { emoji: '\u{1F1F5}\u{1F1ED}', name: 'flag philippines', keywords: ['philippines', 'filipino'], category: 'flags', popularityRank: 528 },
  { emoji: '\u{1F1EE}\u{1F1EA}', name: 'flag ireland', keywords: ['ireland', 'irish'], category: 'flags', popularityRank: 529 },
  { emoji: '\u{1F1F5}\u{1F1F1}', name: 'flag poland', keywords: ['poland', 'polish'], category: 'flags', popularityRank: 530 },
];

// ---------------------------------------------------------------------------
// Combined export
// ---------------------------------------------------------------------------

export const EMOJI_DATA: EmojiItem[] = [
  ...smileys,
  ...people,
  ...animals,
  ...food,
  ...travel,
  ...activities,
  ...objects,
  ...symbols,
  ...flags,
];
